#!/usr/bin/env zsh

# List all files colorized in long format
alias l="ls -lF -G"

# List the available scripts
alias scripts="ls -la ~/.shell/scripts"

# List all files colorized in long format, including dot files
alias ll="ls -laF -G"

# List only directories
alias lsd="ls -lF -G | grep --color=never '^d'"

# Always use color output for `ls`
alias ls="command ls -G"
export LS_COLORS='no=00:fi=00:di=01;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:'

# Enable aliases to be sudo’ed
alias sudo='sudo '

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# View HTTP traffic
alias sniff="sudo ngrep -d 'en1' -t '^(GET|POST) ' 'tcp and port 80'"
alias httpdump="sudo tcpdump -i en1 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""

###############################################################################
# Git                                                                         #
###############################################################################

# add
alias ga='git add'                           # add

# branch
alias gb='git branch --sort=-committerdate | head -n 5' # Last 5 branches ordered recent commits
alias gbv='git branch -v'                     # branch (verbose)

# commit
alias gc='git commit -v'                     # commit with message
alias gca='git commit -am'                   # commit all with message
alias gcm='git commit -m'                    # commit with message
alias gc-a='git commit --amend'              # ammend your last commit

# checkout
alias gco='git checkout'                     # checkout
alias gnb='git checkout -b'                  # create and switch to a new branch (mnemonic: "git new branch branchname...")

# cherry-pick
alias gcp='git cherry-pick -x'               # grab a change from a branch

# diff
alias gd='git diff'                          # diff unstaged changes
alias gdc='git diff --cached'                # diff staged changes

# log
alias gl='git log --graph --date=short'
alias gls="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"

# pull
alias gpl='git pull'                         # pull

# push
alias gps='git push'                         # push
alias gpsu='git push -u origin HEAD'         # git push & set upstream to origin master
alias gpsf='git push --force-with-lease'     # force push, bail on upstream changes.

# rebase
alias grc='git rebase --continue'            # continue rebase
alias grs='git rebase --skip'                # skip rebase

# remote
alias gr='git remote -v'                     # show remotes (verbose)

# stash
alias gss='git stash'                        # stash changes
alias gsl='git stash list'                   # list stashes
alias gsp='git stash pop'                    # pop changes (restore & remove)
alias gsa='git stash apply'                  # apply stash (restore changes)
alias gsd='git stash drop'                   # drop stashes (destory changes)

# status
alias gs='git status'                        # status
alias gst='git status'                       # status
alias gstat='git status'                     # status


###############################################################################
# Development                                                                 #
###############################################################################

alias svgo-sketch='svgo --enable=removeTitle --enable=removeDesc --enable=removeDoctype --enable=removeEmptyAttrs --enable=removeUnknownsAndDefaults --enable=removeUnusedNS --enable=removeEditorsNSData --enable=convertTransform --enable=sortAttrs --enable=cleanupIDs --pretty --multipass --indent 2'

function be {
  bundle exec "$@";
}

alias rmod='rspec `git ls-files --modified --others spec`'
